/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Moshe } from "./Moshe";
import { MosheCountArgs } from "./MosheCountArgs";
import { MosheFindManyArgs } from "./MosheFindManyArgs";
import { MosheFindUniqueArgs } from "./MosheFindUniqueArgs";
import { DeleteMosheArgs } from "./DeleteMosheArgs";
import { MosheService } from "../moshe.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Moshe)
export class MosheResolverBase {
  constructor(
    protected readonly service: MosheService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Moshe",
    action: "read",
    possession: "any",
  })
  async _moshesMeta(
    @graphql.Args() args: MosheCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Moshe])
  @nestAccessControl.UseRoles({
    resource: "Moshe",
    action: "read",
    possession: "any",
  })
  async moshes(@graphql.Args() args: MosheFindManyArgs): Promise<Moshe[]> {
    return this.service.moshes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Moshe, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Moshe",
    action: "read",
    possession: "own",
  })
  async moshe(
    @graphql.Args() args: MosheFindUniqueArgs
  ): Promise<Moshe | null> {
    const result = await this.service.moshe(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Moshe)
  @nestAccessControl.UseRoles({
    resource: "Moshe",
    action: "delete",
    possession: "any",
  })
  async deleteMoshe(
    @graphql.Args() args: DeleteMosheArgs
  ): Promise<Moshe | null> {
    try {
      return await this.service.deleteMoshe(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
